PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX lego: <http://geneontology.org/lego/>
PREFIX : <http://model.geneontology.org/>

DELETE {
  GRAPH ?g {
    ?s ?p ?o
  }
}
WHERE {
  # This is all triples from noctua cam graphs, including inferred graphs
  {
    ?g :graphType :noctuaCam .
    ?g lego:modelstate ?state .
    FILTER(?state != "production")
  }
  UNION
  {
    ?g :graphType :noctuaInferences .
    ?g prov:wasDerivedFrom ?asserted .
    ?asserted lego:modelstate ?state .
    FILTER(?state != "production")
  }
  GRAPH ?g {    
    ?s ?p ?o .
  }
}
