PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX : <http://geneontology.org/>

INSERT {
  GRAPH ?g {
    ?g :graphType :gafCam
  }
}
WHERE {
  {
    SELECT DISTINCT ?g WHERE {
      GRAPH ?g {
        ?s ?p ?o
      }
    }
  }
  FILTER regex(str(?g), "owlapi:ontology[0-9].*")
}
