PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX : <http://geneontology.org/>

INSERT {
  GRAPH ?inf {
    ?inf :inferredFrom ?g .
  }
}
WHERE {
  {
  	SELECT DISTINCT ?inf
  	WHERE {
      GRAPH ?inf {
        ?s ?p ?o .
      }
  	}
  }
  FILTER regex(str(?inf), "http:\\/\\/model\\.geneontology\\.org\\/.+_inferred")
  BIND (URI(replace(str(?inf), "_inferred", "")) as ?g)
}
