PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX prov: <http://www.w3.org/ns/prov#>

INSERT {
  GRAPH <http://purl.obolibrary.org/obo/go/extensions/go-graphstore.owl#subclass_closure> {
    ?sub rdfs:subClassOf ?super .
    <http://purl.obolibrary.org/obo/go/extensions/go-graphstore.owl#subclass_closure> prov:wasDerivedFrom <http://purl.obolibrary.org/obo/go/extensions/go-graphstore.owl> .
  }
}
WHERE {
  GRAPH <http://purl.obolibrary.org/obo/go/extensions/go-graphstore.owl> {
    ?sub rdfs:subClassOf* ?super .
    FILTER(isIRI(?sub))
    FILTER(isIRI(?super))
  }
}
