PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX : <http://model.geneontology.org/>

INSERT {
  GRAPH ?g {
    ?g :graphType :noctuaInferences .
  }
}
WHERE {
  GRAPH ?g {
    ?g prov:wasDerivedFrom ?ag .
  }
  # Copied asserted models also have wasDerivedFrom links
  FILTER NOT EXISTS {
    ?g <http://geneontology.org/lego/modelstate> ?state .
  }
}
