PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://geneontology.org/>

INSERT {
  GRAPH ?g {
    ?g :graphType :noctuaCam .
  }
  GRAPH ?inf {
    ?inf :graphType :noctuaCam .
  }
}
WHERE {

  GRAPH ?g {
    ?g a owl:Ontology .
    ?g <http://purl.org/dc/elements/1.1/title> ?title .
  }

  GRAPH ?inf {
    ?inf :inferredFrom ?g .
  }
}
