* How to get the GO site going from the file tarball and DB dump
  Using a clean Ubuntu AWS 14.04 image as the example.
** Packages
   sudo apt-get -u install apache2 apache2-utils php5-gd mysql-client mysql-server libapache2-mod-php5 php5-mysql
   And because we're not savages:
   sudo apt-get -u install emacs24 emacs24-el
** Directory layout and file tree
   sudo mkdir -p /srv/go-site
   sudo chown ubuntu /srv/go-site
   sudo chgrp ubuntu /srv/go-site
   cd /srv/go-site
   [assume existence of /srv/go-site/drupal-file-tree.tar.bz2]
   tar -jxvf drupal-file-tree.tar.bz2
   sudo chgrp -R www-data htdocs
** MySQL
   [assume existence of /srv/go-site/mysql.sql.bz2]
   bunzip2 mysql.sql.bz2
   mysqladmin -u root -p create drupal_expo
   mysql -u root -p
   mysql> GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES ON drupal_expo.* TO 'drupal_admin'@'localhost' IDENTIFIED BY 'AABBCC';
   mysql> FLUSH PRIVILEGES;
   mysql -u root drupal_expo -h localhost -p < mysql.sql
** Final Drupal adjustments
   Password must match above's "AABBCC" (from user creation) in
   htdocs/sites/default/settings.php.
** Apache 2 setup
   sudo a2enmod rewrite
   [change in default configuration in /etc/apache2/sites-enabled/000-default.conf]
   ---
   #DocumentRoot /var/www/html
   DocumentRoot /srv/go-site/htdocs
   <Directory /srv/go-site/htdocs>
    RewriteEngine On
    RewriteBase /
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php?q=$1 [L,QSA]
   </Directory>
   ---
   [enable /srv in /etc/apache2/apache2.conf]
   <Directory /srv/>
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
   </Directory>
   ---
   sudo service apache2 restart
** Miscellaneous niceties
*** XSS scripting protection for http://drupal.org/SA-CORE-2013-003
   In /tmp/.htaccess:
   ---
   # Turn off all options we don't need.
   Options None
   Options +FollowSymLinks
   
   # Set the catch-all handler to prevent scripts from being executed.
   SetHandler Drupal_Security_Do_Not_Remove_See_SA_2006_006
   <Files *>
     # Override the handler again if we're run later in the evaluation list.
     SetHandler Drupal_Security_Do_Not_Remove_See_SA_2013_003
   </Files>
   
   # If we know how to do it safely, disable the PHP engine entirely.
   <IfModule mod_php5.c>
     php_flag engine off
   </IfModule>
   
   Deny from all
*** Cron
   00 23 * * * wget -qO- http://???/cron.php?cron_key=??? &> /dev/null

