# This is a basic workflow to help you get started with Actions

name: GOex

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate_goex_yaml:
    runs-on: ubuntu-latest
    container: geneontology/dev-base:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install LinkML
      run: apt-get update -qq && apt-get install -y python3 python3-pip mmv -qq
    - name: Install python stuff
      run: pip3 install linkml
    ## Test 1.
    - name: Test goex.yaml
      run: |
        linkml-validate -s metadata/goex.linkmlschema.yaml metadata/goex.yaml
    ## Test 2.
    ## Necessary as the above may not work: https://github.com/linkml/linkml/issues/1542
    - name: Test goex.yaml via JSON
      run: |
        linkml-convert -t json -s metadata/goex.linkmlschema.yaml metadata/goex.yaml
